---
- hosts: deploy
  pre_tasks:
    - git:
        repo: ssh://git@github.com/cympfh/longinus.git
        dest: $HOME/git/longinus
    - template:
        src: config.yml.j2
        dest: $HOME/git/longinus/config.yml
  roles:
    - role: screen_deploy
      vars:
        name: longinus
        shell: cd $HOME/git/longinus && npm i && node server.js
