- name: working directory
  file:
    path: /home/ubuntu/git/{{ tag }}
    state: directory
    force: yes
- name: copy files
  copy:
    src: "{{ item }}"
    dest: "/home/ubuntu/git/{{ tag }}/{{ item }}"
    force: yes
  with_items: "{{ copy_files }}"
