---
- hosts: deploy
  pre_tasks:
    - git:
        repo: ssh://git@github.com/cympfh/dosoku.git
        dest: $HOME/git/dosoku
    - template:
        src: ichigo.config.sh
        dest: $HOME/git/dosoku/ichigo-slack/config.sh
        mode: '0600'
  roles:
    - role: screen_deploy
      vars:
        name: ichigo
        shell: cd $HOME/git/dosoku/ichigo-slack && bash ichigo.sh
