---
- hosts: deploy
  pre_tasks:
    - git:
        repo: ssh://git@github.com/cympfh/twitter2slack.git
        dest: $HOME/git/twitter2slack
    - template:
        src: t2s.config.yml
        dest: $HOME/git/twitter2slack/config.yml
        mode: '0600'
  roles:
    - role: screen_deploy
      vars:
        name: t2s
        shell: cd $HOME/git/twitter2slack && make run
