---
- hosts: deploy
  vars:
  - repo: https://github.com/cympfh/twitter2slack
  - tag: twitter2slack
  - port: 8085
  - full_command: >-
      docker run -d --restart=always --name={{ tag }}
      -p {{ port }}:{{ port }}
      -e PORT={{ port }}
      -e "SLACK_CHANNEL=#timeline"
      -e SLACK_WEBHOOK={{ slack.webhook }}
      {{ tag }}
  roles:
  - docker_build
  - docker_deploy
