---
- hosts: deploy
  vars:
    copy_files:
      - Dockerfile
      - nginx.conf
    tag: nginx
    full_command: >-
      docker run -d --restart=always --name=nginx
        -p 80:80
        -p 443:443
        -v /opt/nginx-certs:/etc/nginx/certs:ro
        nginx
  roles:
    - docker_build
    - docker_deploy
