---
- hosts: deploy
  pre_tasks:
    - git:
        repo: ssh://git@github.com/cympfh/ampeloss.git
        dest: $HOME/git/ampeloss
    - template:
        src: mcast.config.sh
        dest: $HOME/git/ampeloss/mastodon-broadcast/config.sh
        mode: '0600'
    - template:
        src: mcast.dest.list
        dest: $HOME/git/ampeloss/mastodon-broadcast/dest.list
        mode: '0600'
  roles:
    - role: screen_deploy
      vars:
        name: mcast
        shell: cd $HOME/git/ampeloss/mastodon-broadcast && bash ./mcast

