---
- hosts: deploy
  vars:
  - repo: https://github.com/cympfh/booklog-database
  - tag: booklog-database
  - full_command: >-
      docker run -d --restart=always --name=booklog-database
        -p 8084:8084
        booklog-database
        fastapi run ./server.py --host 0.0.0.0 --port 8084
  roles:
  - docker_build
  - docker_deploy
