---
- hosts: deploy
  pre_tasks:
    - git:
        repo: ssh://git@github.com/cympfh/tw-clean.git
        dest: $HOME/git/tw-clean
  roles:
    - role: screen_deploy
      vars:
        name: tw-clean-ampeloss
        shell: cd $HOME/git/tw-clean && bash ./tw-clean ampeloss --margin $(hour 6) --rule ".text | (startswith(\\"@\\") or startswith(\\"RT\\"))"
    - role: screen_deploy
      vars:
        name: tw-clean-cympfh
        shell: cd $HOME/git/tw-clean && bash ./tw-clean cympfh --margin $(hour 6) --rule "((.text|startswith(\\"@\\")|not) and (.text|endswith(\\".\\")|not) and (.extended_entities.media | length) == 0)"
